### ISSUE TITLE
Добавить город

### ISSUE THREAD

**Issue by dimqua** [vshkl/TransLate2#12]
Можете добавить Москву в приложение, например? Что для этого нужно?

**Comment by vshkl** [comment]
Не планирую добавлять другие города. Москву в частности не вижу смысла добавлять потому, что уже есть Yandex.Transport, который умеет показывать движения общественного транспорта в реальном времени.
Если в общем, то нужен API, откуда можно получить остановки и запрашивать данные о движении траснпорта.
